site_name: docstr - A document string minor mode
site_description: Document String tool for Emacs
site_url: https://jcs-elpa.github.io/docstr
site_author: jcs090218@gmail.com

nav:
  - Home:
    - Overview: README.md
  - Languages:
    - All Languages: page/all_languages.md
    - ActionScript: page/langs/actionscript.md
    - C: page/langs/c.md
    - C++: page/langs/c++.md
    - C#: page/langs/csharp.md
    - Go: page/langs/go.md
    - Groovy: page/langs/groovy.md
    - Java: page/langs/java.md
    - JavaScript: page/langs/javascript.md
    - Lua: page/langs/lua.md
    - PHP: page/langs/php.md
    - Python: page/langs/python.md
    - Ruby: page/langs/ruby.md
    - Rust: page/langs/rust.md
    - Scala: page/langs/scala.md
    - TypeScript: page/langs/typescript.md
  - Changelog:
    - page/CHANGELOG.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: etc/logo.png
  favicon: etc/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jcs-elpa/docstr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jenchieh94

repo_name: jcs-elpa/docstr
repo_url: https://github.com/jcs-elpa/docstr

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - meta
  - toc:
      permalink: '#'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
  - rss

google_analytics:
  - UA-165661257-1
  - auto
